version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/processor"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/enabler"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10